### PR TITLE
feat: add an extension point for custom extractor and update dependencies

### PR DESCRIPTION
**Pull request by trustin**
- Allow a user to customize `@postlight/parser` so that he or she can add a custom extractor, by mounting `/app/customizer`.
- Add a section about how to add a custom extractor to `README.md`
- Update dependencies
  - Replace `@postlight/mercury-parser` with the latest version of `@postlight/parser`.
  - Update the base Docker image from 13-alpine to 18-alpine.
- Miscellaneous:
  - Remove `yarn.lock` which seems unused.

### CODE REVIEW

**Comment by trustin** [comment]
Gentle ping - @HenryQW

**Comment by HenryQW** [comment]
Hi Trustin thanks for the PR, can you resolve the conflicts?

**Comment by trustin** [comment]
@HenryQW Conflict resolved :wink:

**Comment by HenryQW** [comment]
Thanks @trustin

**Pull request merged**
